### ISSUE TITLE
infinity managed challenge

### ISSUE THREAD

**Issue by ReferTV** [SocolSRT/cloudflare-rules#2]
For me, these rules cause infinity managed challenge since CloudFlare introduced the security page update

**Comment by SocolSRT** [comment]
hello, this usually happens when your browser or provider is too suspicious (for example, the tor browser), there may also be problems on the side of the hosting provider or in the settings cloudflare. 

if you still can't solve the problem, disable the rule Threat Check

for more information, contact support cloudflare
